SaafiSystems/Models/LoadCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaafiSystems.Models
{
    public class LoadCategory
    {
        public int ID { get; set; }
        public string Name { get; set; }

        public IList<Load> Loads { get; set; }


    }
}

SaafiSystems/Controllers/LoadCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using SaafiSystems.Models;
using System.Collections.Generic;
using SaafiSystems.ViewModels;
using SaafiSystems.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SaafiSystems.Controllers
{
    public class LoadCategoryController : Controller
    {
        private readonly SaafiDbContext context;

        public LoadCategoryController(SaafiDbContext dbContext)
        {
            this.context = dbContext;
        }
        public async Task<IActionResult> Index(int? page)
        {
            var loadCategories = from lCat in context.LoadCategories
                                    select lCat;
            int pageSize = 3;
            return View(await PaginatedList<LoadCategory>.CreateAsync(loadCategories.AsNoTracking(), page ?? 1, pageSize));

        }
       

        public IActionResult Add()
        {
            AddLoadCategoryViewModel addLoadCategoryViewModel =
                new AddLoadCategoryViewModel();
            return View(addLoadCategoryViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddLoadCategoryViewModel addLoadCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                LoadCategory newLoadCategory = new LoadCategory
                {
                    Name = addLoadCategoryViewModel.Name,



                };

                context.LoadCategories.Add(newLoadCategory);
                context.SaveChanges();

                return Redirect("/LoadCategory");
            }

            return View(addLoadCategoryViewModel);
        }
        public IActionResult Remove(int ID)
        {
            var loadCat = context.LoadCategories.Single(e => e.ID == ID);
            if (loadCat != null)
                context.LoadCategories.Remove(loadCat);

            context.SaveChanges();

            return Redirect("/LoadCategory");


        }

        [HttpPost]
        public IActionResult Remove(int[] loadCategoryIds)
        {
            foreach (int loadCategoryId in loadCategoryIds)
            {
                LoadCategory theLoadCategory = context.LoadCategories.Single(c => c.ID == loadCategoryId);
                context.LoadCategories.Remove(theLoadCategory);
            }

            context.SaveChanges();

            return Redirect("/LoadCategory");
        }
    }
}

SaafiSystems/Controllers/LoadController.cs
using Microsoft.AspNetCore.Mvc;
using SaafiSystems.Models;
using System.Collections.Generic;
using SaafiSystems.ViewModels;
using SaafiSystems.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

using PagedList.Core;

using System.ComponentModel.DataAnnotations;
namespace SaafiSystems.Controllers
{
    public class LoadController : Controller
    {
        private readonly SaafiDbContext context;

        public LoadController(SaafiDbContext dbContext)
        {
            this.context = dbContext;
        }

        // GET: /<controller>/
        public async Task< IActionResult> Index(int? page)
        {
            
            var loads = from l in context.Loads.Include(c => c.LoadCategory).Include(c => c.OwnerLoads)
            select l;
            int pageSize = 3;
            return View(await PaginatedList<Load>.CreateAsync(loads.AsNoTracking(), page ?? 1, pageSize));
        }

        public IActionResult Add()
        {
            //TODO: #6Render Owner/Operator List along Load Categories 
            IList<LoadCategory> loadCategories = context.LoadCategories.ToList();

            AddLoadViewModel addLoadViewModel =
                new AddLoadViewModel(context.LoadCategories.ToList(), null);
            return View(addLoadViewModel);
        }


        [HttpPost]
        public IActionResult Add(AddLoadViewModel addLoadViewModel)
        {
            if (ModelState.IsValid)
            {
                LoadCategory newLoadCategory =
                    context.LoadCategories.Single(c => c.ID == addLoadViewModel.LoadCategoryID);

                Load newLoad = new Load
                {

                    Date = addLoadViewModel.Date,
                    Reference = addLoadViewModel.Reference,
                    Description = addLoadViewModel.Description,
                    Owner = addLoadViewModel.Owner,
                    Amount = addLoadViewModel.Amount,
                    LoadCategory = newLoadCategory,

                };



                context.Loads.Add(newLoad);
                context.SaveChanges();

                return Redirect("/Load");
            }

            return View(addLoadViewModel);
        }

        public IActionResult Remove(int ID)
        {
            var ld = context.Loads.Single(e => e.ID == ID);
            if (ld != null)
                context.Loads.Remove(ld);

            context.SaveChanges();

            return Redirect("/Load");


        }
        [HttpPost]
        public IActionResult Remove(int[] loadIds)
        {
            foreach (int loadId in loadIds)
            {
                Load theLoads = context.Loads.Single(c => c.ID == loadId);
                context.Loads.Remove(theLoads);
            }

            context.SaveChanges();

            return Redirect("/Load");
        }
        [HttpPost]
        public IActionResult Category(int id)
        {
            if (id == 0)
            {
                Redirect("/Load");
            }

            LoadCategory theCategory = context.LoadCategories
                .Include(cat => cat.Loads)
                .Single(cat => cat.ID == id);

            ViewBag.Title = "Loads in Category" + theCategory.Name;
            return View("Index", theCategory.Loads);
        }
        [HttpPost]
        public IActionResult RevCategory(int id)
        {
            if (id == 0)
            {
                Redirect("/Load");
            }

            RevenueCategory theCategory = context.RevenueCategories
                .Include(cat => cat.Loads)
                .Single(cat => cat.ID == id);

            ViewBag.Title = "Loads in Revenu Category" + theCategory.Name;
            return View("Index", theCategory.Loads);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var load = context.Loads.SingleOrDefault((l) => l.ID == id);
            if (load == null)
            {
                return NotFound();
            }
            List<LoadCategory> newLoadCategory =
                    new List<LoadCategory>() { context.LoadCategories.Single(c => c.ID == load.LoadCategoryID) };
            return View(new AddLoadViewModel(newLoadCategory, load));
        }


        [HttpPost]
        public async Task<IActionResult> Edit(AddLoadViewModel addLoadViewModel)
        {
            //TODO: #5 Edit Action Not fulle working
            var load = context.Loads.SingleOrDefault((l) => l.ID == addLoadViewModel.ID);

            if (load == null)
            {
                return NotFound();
            }
            var newLoadCategories = context.LoadCategories;

            var viewModel = new AddLoadViewModel(newLoadCategories, load);

            var existingLoadCateogry = context.LoadCategories.SingleOrDefault(c => c.ID == load.LoadCategoryID);

            if (existingLoadCateogry != null)
            {
                viewModel.LoadCategory = existingLoadCateogry;
                viewModel.LoadCategoryID = existingLoadCateogry.ID;

            }
            
            {
                await context.SaveChangesAsync();
                Redirect("/Load");


            }
            return View(viewModel);

        }
    }                
}

SaafiSystems/Views/LoadCategory/Add.cshtml
@model SaafiSystems.ViewModels.AddLoadCategoryViewModel

<div class="page-header" style="background:white">
    <h1 style=" font-size: 21px;color: #0b131d; font-weight: 400;font-size: 21px;margin-top: 20px;margin-bottom: 10px;font-family: inherit;font-weight: 400;line-height: 1.1;color: inherit;margin: .67em 0; font-size: 2em; box-sizing: border-box;display: block;font-size: 2em; font-weight: bold;">
        Add Load Category
        <a asp-controller="LoadCategory" asp-action="Add" class="hidden-xs btn btn-primary pull-right">+ Add Driver</a> <a asp-controller="Load" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ Add Category</a>
        <a asp-controller="Load" asp-action="Add" class="hidden-xs btn btn-success pull-right">+ New Payroll Entry</a> <a asp-controller="Load" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ New Trip Entry</a>
    </h1>
</div>
<form asp-controller="LoadCategory" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <input type="submit" class="hidden-xs btn btn-success" value=" + Submit New Category" />
   

</form>

SaafiSystems/Views/LoadCategory/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SaafiSystems/Views/LoadCategory/Index.cshtml
@model PaginatedList<SaafiSystems.Models.LoadCategory>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="page-header" style="background:white">
    <h1 style=" font-size: 21px;color: #0b131d; font-weight: 400;font-size: 21px;margin-top: 20px;margin-bottom: 10px;font-family: inherit;font-weight: 400;line-height: 1.1;color: inherit;margin: .67em 0; font-size: 2em; box-sizing: border-box;display: block;font-size: 2em; font-weight: bold;">
        Trip Categories
        <form asp-controller="Reports" asp-action="Index" class="navbar-form navbar-left" role="search" method="get">
            <div class="form-group">
                <p>
                    <input type="text" name="searchString" class="form-control" placeholder="Search your trips, loads and more" value="@ViewData["CurrentFilter"]" />
                    <input type="submit" value="Search" class="btn btn-group-xs " />
                </p>
            </div>
        </form>
        <a asp-controller="LoadCategory" asp-action="Add" class="hidden-xs btn btn-primary pull-right">+ Add Category</a> <a asp-controller="LoadCategory" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ Add Category</a>
        <a asp-controller="Load" asp-action="Add" class="hidden-xs btn btn-success pull-right">+ New Trip</a> <a asp-controller="Load" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ New Trip</a>
    </h1>
</div>


@if (Model.Count == 0)
{
    <p>No Trip Categories yet</p>

}
<form asp-controller="LoadCategory" asp-action="Remove" method="post">
    <table class="table table-striped ">
        <tr>
            <th>Reference</th>
            <th>Expense Type</th>
            <th>Action</th>
            <th></th>
        </tr>

        @foreach (var category in Model)
        {

            <tr>
                <td><a asp-controller="Load" asp-route-id="@category.ID">@category.ID</a></td>
                <td><a asp-controller="Load" asp-route-id="@category.ID">@category.Name</a></td>
                <td>

                    <a href="/loadcategory/edit/@category.ID" class="btn btn-info btn-xs">Edit</a>
                    @*@*<input type="checkbox" name="expenseIds" id="@expense.ID" value="@expense.ID" class="btn btn-danger btn-sm" />*@
                    @*<input type="submit" value="Delete" class="btn btn-info btn-sm" />*@
                </td>
                <td>
                    <a href="/loadcategory/remove/@category.ID" class="btn btn-danger btn-xs">Delete</a>
                    @*<input type="submit" value="Edit" class="btn btn-info btn-sm" />*@
                </td>
            </tr>

        }

    </table>

</form>



<p><a asp-controller="LoadCategory" asp-action="Add" class="btn btn-info btn-sm">Add Category</a></p>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled btn">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled btn">
    Next
</a>
</br>

SaafiSystems/Views/LoadCategory/Remove.cshtml
@model List<SaafiSystems.Models.LoadCategory>

<h1>@ViewBag.title</h1>
@if (Model.Count == 0)
{
    <p>No load categoris to remove</p>

}

<form asp-controller="LoadCategory" asp-action="Remove" method="post">


    @foreach (var entry in Model)
    {
        <input type="checkbox" name="loadCategoryIds" id="@entry.ID" value="@entry.ID" />
        <label for="@entry.ID">@entry.Name</label>
        <br />
    }

    <input type="submit" value="Remove Selected Category(s)" />
</form>