SaafiSystems/Controllers/DriverController.cs
using Microsoft.AspNetCore.Mvc;
using SaafiSystems.Models;
using System.Collections.Generic;
using SaafiSystems.ViewModels;
using SaafiSystems.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace SaafiSystems.Controllers
{
    public class DriverController : Controller
    {
        private readonly SaafiDbContext context;

        

        public DriverController(SaafiDbContext dbContext)
        {
            this.context = dbContext;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index(int? page)
        {
            
            var drivers = from d in context.Drivers.Include(c => c.DriverName)
                        select d;
            int pageSize = 3;
            return View(await PaginatedList<Driver>.CreateAsync(drivers.AsNoTracking(), page ?? 1, pageSize));
            
        }

        public IActionResult Add()
        {
            IList<DriverName> driverNames = context.DriverNames.ToList();
            AddDriverLoadViewModel addDriverLoadViewModel =
                new AddDriverLoadViewModel(context.DriverNames.ToList(), null);
            return View(addDriverLoadViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddDriverLoadViewModel addDriverLoadViewModel)
        {
            if (ModelState.IsValid)
            {
                DriverName newDriver =
                    context.DriverNames.Single(c => c.ID == addDriverLoadViewModel.DriverNameID);
                // Add the new cheese to my existing cheeses
                Driver newTrip = new Driver
                {

                    Date = addDriverLoadViewModel.Date,
                    Reference = addDriverLoadViewModel.Reference,
                    Description = addDriverLoadViewModel.Description,
                    LoadMiles = addDriverLoadViewModel.LoadMiles,
                    DeadMiles = addDriverLoadViewModel.DeadMiles,

                    Rate = addDriverLoadViewModel.Rate,
                    DriverName = newDriver
                };

                context.Drivers.Add(newTrip);
                context.SaveChanges();

                return Redirect("/Driver");
            }

            return View(addDriverLoadViewModel);
        }

      
        public IActionResult Remove(int ID)
        {
            var dri = context.Drivers.Single(e => e.ID == ID);
            if (dri != null)
                context.Drivers.Remove(dri);

            context.SaveChanges();

            return Redirect("/Driver");


        }
        [HttpPost]
        public IActionResult Remove(int[] driverIds)
        {
            foreach (int driverId in driverIds)
            {
                Driver theDriverEntry = context.Drivers.Single(c => c.ID == driverId);
                context.Drivers.Remove(theDriverEntry);
            }

            context.SaveChanges();

            return Redirect("/Driver");
        }
        [HttpPost]
        public IActionResult Names(int id)
        {
            if (id == 0)
            {
                Redirect("/Name");
            }

            DriverName theDriver = context.DriverNames
                .Include(cat => cat.Drivers)
                .Single(cat => cat.ID == id);


            ViewBag.Title = "Entries for Driver" + theDriver.Name;
            return View("Index", theDriver.Drivers);
        }

        public IActionResult ViewDriver()
        {
            IList<DriverName> driverName = context.DriverNames.ToList();
            ViewDriverViewModel viewDriverLoadsViewModel = new ViewDriverViewModel(context.DriverNames.ToList());

            return View(viewDriverLoadsViewModel);

        }


        [HttpPost]
        public IActionResult ViewDriver(ViewDriverViewModel viewDriverLoadsViewModel)
        {
            if (ModelState.IsValid)
            {

                return Redirect(string.Format("/Driver/DriverTrips/{0}", viewDriverLoadsViewModel.DriverNameID));
            }

            return View(viewDriverLoadsViewModel);
        }

        public IActionResult DriverTrips(int id)
        {

            List<Driver> drivers = context.
                Drivers
                .Include(c => c.DriverName)
                .Where(c => c.DriverNameID == id).
                ToList();
            DriverName driverName = context.DriverNames.Single(c => c.ID == id);
            DriverLoadsViewModel driverLoads = new DriverLoadsViewModel
            {
                Drivers = drivers,
             
            };
            ViewBag.title = driverName.Name;
            return View(driverLoads);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var driver = context.Drivers.SingleOrDefault((l) => l.ID == id);
            if (driver == null)
            {
                return NotFound();
            }
            List<DriverName> newDriverName =
                    new List<DriverName>() { context.DriverNames.Single(c => c.ID == driver.DriverNameID) };
            return View(new AddDriverLoadViewModel(newDriverName, driver));
        }

        
        [HttpPost]
        public async Task<IActionResult> Edit(AddDriverLoadViewModel addDriverLoadViewModel)
        {
            var driver = context.Drivers.SingleOrDefault((l) => l.ID == addDriverLoadViewModel.ID);
            if (driver == null)
            {
                return NotFound();
            }
            var newDriverNames = context.DriverNames;

            var viewModel = new AddDriverLoadViewModel(newDriverNames, driver);

            var existingDriverName = context.DriverNames.SingleOrDefault(c => c.ID == driver.DriverNameID);

            if (existingDriverName != null)
            {
                viewModel.DriverName = existingDriverName;
                viewModel.DriverNameID = existingDriverName.ID;
            }

            return View(viewModel);
        }
    }
}

SaafiSystems/Controllers/LoadController.cs
using Microsoft.AspNetCore.Mvc;
using SaafiSystems.Models;
using System.Collections.Generic;
using SaafiSystems.ViewModels;
using SaafiSystems.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

using PagedList.Core;

using System.ComponentModel.DataAnnotations;
namespace SaafiSystems.Controllers
{
    public class LoadController : Controller
    {
        private readonly SaafiDbContext context;

        public LoadController(SaafiDbContext dbContext)
        {
            this.context = dbContext;
        }

        // GET: /<controller>/
        public async Task< IActionResult> Index(int? page)
        {
            
            var loads = from l in context.Loads.Include(c => c.LoadCategory).Include(c => c.OwnerLoads)
            select l;
            int pageSize = 3;
            return View(await PaginatedList<Load>.CreateAsync(loads.AsNoTracking(), page ?? 1, pageSize));
        }

        public IActionResult Add()
        {
            //TODO: #6Render Owner/Operator List along Load Categories 
            IList<LoadCategory> loadCategories = context.LoadCategories.ToList();

            AddLoadViewModel addLoadViewModel =
                new AddLoadViewModel(context.LoadCategories.ToList(), null);
            return View(addLoadViewModel);
        }


        [HttpPost]
        public IActionResult Add(AddLoadViewModel addLoadViewModel)
        {
            if (ModelState.IsValid)
            {
                LoadCategory newLoadCategory =
                    context.LoadCategories.Single(c => c.ID == addLoadViewModel.LoadCategoryID);

                Load newLoad = new Load
                {

                    Date = addLoadViewModel.Date,
                    Reference = addLoadViewModel.Reference,
                    Description = addLoadViewModel.Description,
                    Owner = addLoadViewModel.Owner,
                    Amount = addLoadViewModel.Amount,
                    LoadCategory = newLoadCategory,

                };



                context.Loads.Add(newLoad);
                context.SaveChanges();

                return Redirect("/Load");
            }

            return View(addLoadViewModel);
        }

        public IActionResult Remove(int ID)
        {
            var ld = context.Loads.Single(e => e.ID == ID);
            if (ld != null)
                context.Loads.Remove(ld);

            context.SaveChanges();

            return Redirect("/Load");


        }
        [HttpPost]
        public IActionResult Remove(int[] loadIds)
        {
            foreach (int loadId in loadIds)
            {
                Load theLoads = context.Loads.Single(c => c.ID == loadId);
                context.Loads.Remove(theLoads);
            }

            context.SaveChanges();

            return Redirect("/Load");
        }
        [HttpPost]
        public IActionResult Category(int id)
        {
            if (id == 0)
            {
                Redirect("/Load");
            }

            LoadCategory theCategory = context.LoadCategories
                .Include(cat => cat.Loads)
                .Single(cat => cat.ID == id);

            ViewBag.Title = "Loads in Category" + theCategory.Name;
            return View("Index", theCategory.Loads);
        }
        [HttpPost]
        public IActionResult RevCategory(int id)
        {
            if (id == 0)
            {
                Redirect("/Load");
            }

            RevenueCategory theCategory = context.RevenueCategories
                .Include(cat => cat.Loads)
                .Single(cat => cat.ID == id);

            ViewBag.Title = "Loads in Revenu Category" + theCategory.Name;
            return View("Index", theCategory.Loads);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var load = context.Loads.SingleOrDefault((l) => l.ID == id);
            if (load == null)
            {
                return NotFound();
            }
            List<LoadCategory> newLoadCategory =
                    new List<LoadCategory>() { context.LoadCategories.Single(c => c.ID == load.LoadCategoryID) };
            return View(new AddLoadViewModel(newLoadCategory, load));
        }


        [HttpPost]
        public async Task<IActionResult> Edit(AddLoadViewModel addLoadViewModel)
        {
            //TODO: #5 Edit Action Not fulle working
            var load = context.Loads.SingleOrDefault((l) => l.ID == addLoadViewModel.ID);

            if (load == null)
            {
                return NotFound();
            }
            var newLoadCategories = context.LoadCategories;

            var viewModel = new AddLoadViewModel(newLoadCategories, load);

            var existingLoadCateogry = context.LoadCategories.SingleOrDefault(c => c.ID == load.LoadCategoryID);

            if (existingLoadCateogry != null)
            {
                viewModel.LoadCategory = existingLoadCateogry;
                viewModel.LoadCategoryID = existingLoadCateogry.ID;

            }
            
            {
                await context.SaveChangesAsync();
                Redirect("/Load");


            }
            return View(viewModel);

        }
    }                
}

SaafiSystems/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SaafiSystems</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">
            <div class="navbar-header">
                <div class="nav navbar nav">

                    <div class="dropdown">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="width: 35px; height: 5px;  background-color: #d9d9d9; margin: 6px 0">

                            <div class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="width: 35px; height: 5px;  background-color: #d9d9d9; margin: 6px 0"> </div>
                            <div class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="width: 35px; height: 5px;  background-color: #d9d9d9; margin: 6px 0;"></div>
                            <div class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="width: 35px; height: 5px;  background-color: #d9d9d9; margin: 6px 0;"></div>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="List" asp-action="Index">List</a></li>
                            <li><a asp-controller="Load" asp-action="Add">Add Trip</a></li>
                            <li><a asp-controller="Remove" asp-action="Index">Remove Trip</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a asp-controller="Reports" asp-action="Index">Reports</a></li>
                            <li><a asp-controller="Revenue" asp-action="Add">Add Revenue</a></li>
                            <li><a asp-controller="List" asp-action="Index">List</a></li>
                            <li><a asp-controller="Expense" asp-action="Add">Add Expense</a></li>
                            <li><a asp-controller="DriverName" asp-action="Add">Add Driver</a></li>
                            <li><a asp-controller="Edit" asp-action="Index">Edit</a></li>
                        </ul>

                    </div>

                </div>
            </div>

            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav"><li><a asp-area="" asp-controller="Home" asp-action="Index"> Saafi</a></li></ul>
                <form asp-controller="Reports" asp-action="Index" class="navbar-form navbar-left" role="search" method="get">
                    <div class="form-group">
                        <p>
                            <input type="text" name="searchString" class="form-control" placeholder="Search your trips, loads and more" value="@ViewData["CurrentFilter"]" />
                     <input type="submit" value="Search" class="btn btn-group-xs "/>  
                        </p>
                        </div>
                        
                    </form>
                    
               
                <ul class="nav navbar-nav">

                    <li><a asp-controller="Load" asp-action="Add">Add Trip</a></li>
                    <li><a asp-controller="Remove" asp-action="Index">Remove</a></li>
                    <li><a asp-controller="Revenue" asp-action="Index">Revenue</a></li>  
                    <li><a asp-controller="Expense" asp-action="Index">Expense</a></li>
                </ul>
               <ul class="nav navbar-nav navbar-right"><li>@await Html.PartialAsync("_LoginPartial")</li></ul> 
            </div>
        </div>
        </div>
        @*<div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-lg-2">
                    <nav class="navbar navbar-default navbar-fixed-side">
                        <div id="sidemenu-wrapper" style="background: #d9d9d9; min-height: 1387px; width: 201px; margin-left: 0px;">
                            <ul class="sidemenu-nav btn-group-sm" style=" position : absolute; top: 0; width: 200px; margin: 0; margin-top: 10px; padding: 0; list-style: none; display: block; color: #595952; font-family: sans-serif; font-weight: 400; ">
                                <li><br /></li>
                                <li> <strong><a asp-controller="List">Trips<span class="pull-right btn-xs btn-default quick"></span></a><br /></strong></li>
                                <li> <strong><a asp-controller="Process">Company Driver <span class="pull-right btn-xs btn-default quick"></span></a><br /></strong></li>
                                <li> <strong><a asp-controller="Driver" class="navbar-link">Owner Operator</a><br /></strong> </li>
                                <li><strong><a asp-controller="Reports" class="navbar-link">Reports </a><br /> </strong></li>
                                <li><strong><a asp-controller="Load" asp-action="Add" class="navbar-link">Process Load</a><br /> </strong> </li>
                                <li><strong><a asp-controller="Load" asp-action="Remove" class="navbar-link">Remove Load</a><br />  </strong></li>
                                <li><strong><a asp-controller="Load" asp-action="Edit" class="navbar-link">Edit Load</a><br />  </strong></li>
                                
                            </ul>
                        </div>
                    </nav>
                </div>*@
    
                <div class="jumbotron span12 pagination-centered" style="background:white">

                </div>
                <div class="container body-content">

                    <div class="btn-group pull-right" role="group" aria-label="...">
                        <button type="button" class="btn btn-default">The Last 7 Days</button>
                        <button type="button" class="btn btn-default">This month</button>
                        <button type="button" class="btn btn-default">This quarter</button>
                        <button type="button" class="btn btn-default">This year</button>
                    </div>
                    @RenderBody()
                    </div>
        
                    <hr />
                    <footer>
                        <p>&copy; 2017 - SaafiSystems</p>
                    </footer>
       
    
                <environment names="Development">
                    <script src="~/lib/jquery/dist/jquery.js"></script>
                    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
                    <script src="~/js/site.js" asp-append-version="true"></script>
                </environment>
                <environment names="Staging,Production">
                    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                            asp-fallback-test="window.jQuery"
                            crossorigin="anonymous"
                            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
                    </script>
                    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                            crossorigin="anonymous"
                            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
                    </script>
                    <script src="~/js/site.min.js" asp-append-version="true"></script>
                </environment>

                @RenderSection("Scripts", required: false)
</body>

</html>