SaafiSystems/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SaafiSystems.Models
{
    public class Expense
    {
  
        public int ID {get; set;}

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? Date { get; set; }
    
        public string Reference { get; set; }
        public string Owner { get; set; }
        public string Description { get; set; }
        public int Amount { get; set; }

        [Required(ErrorMessage =("Select a Catgory or Add a new one!"))]
        
        public int ExpenseCategoryID { get; set; }
        public ExpenseCategory ExpenseCategory { get; set; }

        public List<OwnerExpense> OwnerExpenses { get; set; }
    }
}

SaafiSystems/Models/Owner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SaafiSystems.Models
{
    public class Owner
    {
        public int ID { get; set; }
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        public string Name { get; set; }

        public IList<OwnerLoad> OwnerLoads { get; set; }

        public IList<OwnerExpense> OwnerExpenses { get; set; }
    }
}

SaafiSystems/ViewModels/OwnerExpenseItemViewModel.cs
using SaafiSystems.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaafiSystems.ViewModels
{
    public class OwnerExpenseItemViewModel
    {

        public IList<OwnerExpense> ExpenseItems { get; set; }
        public Owner Owner { get; set; }
    }
}

SaafiSystems/ViewModels/OwnerItemViewModel.cs
using SaafiSystems.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaafiSystems.ViewModels
{
    public class OwnerItemViewModel
    {

        public IList<OwnerLoad> Items { get; set; }
        public Owner Owner { get; set; }
    }
}

SaafiSystems/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using SaafiSystems.Models;
using System.Collections.Generic;
using SaafiSystems.ViewModels;
using SaafiSystems.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace SaafiSystems.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly SaafiDbContext context;

        public ExpenseController(SaafiDbContext dbContext)
        {
            this.context = dbContext;
        }

        // GET: /<controller>/
        public async Task< IActionResult> Index(int? page)
        {
            //.Include(c => c.Owner).ToList();
            var expenses = from e in context.Expenses.Include(c => c.ExpenseCategory)
                          select e;
            int pageSize = 3;
            return View(await PaginatedList<Expense>.CreateAsync(expenses.AsNoTracking(), page ?? 1, pageSize));
           
        }

        public IActionResult Add()
        {
            IList<ExpenseCategory> expenseCategories = context.ExpenseCategories.ToList();
            AddExpenseViewModel addExpenseViewModel =
                new AddExpenseViewModel(context.ExpenseCategories.ToList(), null);
            return View(addExpenseViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddExpenseViewModel addExpenseViewModel)
        {
            if (ModelState.IsValid)
            {
                ExpenseCategory newCategory =
                    context.ExpenseCategories.Single(c => c.ID == addExpenseViewModel.ExpenseCategoryID);
                // Add the new cheese to my existing cheeses
                Expense newExpense = new Expense
                {

                    Date = addExpenseViewModel.Date,
                    Reference = addExpenseViewModel.Reference,
                    Owner = addExpenseViewModel.Owner,
                  
                    Description = addExpenseViewModel.Description,
                    Amount = addExpenseViewModel.Amount,
                    ExpenseCategory = newCategory
                  
                    
                };

                context.Expenses.Add(newExpense);
                context.SaveChanges();

                return Redirect("/Expense");
            }

            return View(addExpenseViewModel);
        }

        public IActionResult Remove(int ID)
        {
            var exp = context.Expenses.Single(e => e.ID == ID);
            if (exp != null)
                context.Expenses.Remove(exp);

            context.SaveChanges();

            return Redirect("/Expense");

       
        }

        [HttpPost]
        public IActionResult Remove(int[] expenseIds)
        {
            foreach (int expenseId in expenseIds)
            {
                Revenue theRevenue = context.Revenues.Single(c => c.ID == expenseId);
                context.Revenues.Remove(theRevenue);
            }

            context.SaveChanges();

            return Redirect("/Expense");
        }
        [HttpPost]
        public IActionResult Category(int id)
        {
            if (id == 0)
            {
                Redirect("/Category");
            }

            ExpenseCategory theCategory = context.ExpenseCategories
                .Include(cat => cat.Expenses)
                .Single(cat => cat.ID == id);

            /* 
             * IList<Cheese> theCheese = Context.Cheeses
             * .Include(c => c.Category)
             * .Single(c => c.CategoryID ==id)
             .ToList();*/

            ViewBag.Title = "Expenses in Category" + theCategory.Name;
            return View("Index", theCategory.Expenses);
        }
      
        public ViewResult Search(string searchString)
        {
           //IList<Expense> expenses = context.Expenses.Include(c => c.ExpenseCategory).Include(c => c.Owner).ToList();
            var expenses = from c in context.Expenses.Include(c => c.ExpenseCategory).Include(c => c.Owner).ToList()
            select c;

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                expenses = context.Expenses.Where(c =>
               c.Reference.Contains(searchString)
                ||

               c.Date.ToString().Contains(searchString) ||

               c.Description.Contains(searchString) ||

               c.Owner.Contains(searchString));

          
            }
            
            return View(expenses);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var expense = context.Expenses.SingleOrDefault((l) => l.ID == id);
            if (expense == null)
            {
                return NotFound();
            }
            List<ExpenseCategory> newExpenseCategory =
                    new List<ExpenseCategory>() { context.ExpenseCategories.Single(c => c.ID == expense.ExpenseCategoryID) };
            return View(new AddExpenseViewModel(newExpenseCategory, expense));
        }


        [HttpPost]
        public async Task<IActionResult> Edit(AddExpenseViewModel addExpenseViewModel)
        {
            var expense = context.Expenses.SingleOrDefault((l) => l.ID == addExpenseViewModel.ID);
            if (expense == null)
            {
                return NotFound();
            }
            var newExpenseCategories = context.ExpenseCategories;

            var viewModel = new AddExpenseViewModel(newExpenseCategories, expense);

            var existingExpenseCategory = context.ExpenseCategories.SingleOrDefault(c => c.ID == expense.ExpenseCategoryID);

            if (existingExpenseCategory != null)
            {
                viewModel.ExpenseCategory = existingExpenseCategory;
                viewModel.ExpenseCategoryID = existingExpenseCategory.ID;
            }

            return View(viewModel);
        }
    }
}

SaafiSystems/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using SaafiSystems.Data;
using Microsoft.AspNetCore.Mvc;
using SaafiSystems.Models;
using SaafiSystems.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SaafiSystems.Controllers
{
    public class OwnerController : Controller
    {
        private readonly SaafiDbContext context;

        public OwnerController(SaafiDbContext dbContext)
        {
            context = dbContext;
        }
        // GET: /<controller>/
      
        public async Task<IActionResult> Index(int? page)
        {
            var owners = from o in context.Owners
                                    select o;
            int pageSize = 3;
            return View(await PaginatedList<Owner>.CreateAsync(owners.AsNoTracking(), page ?? 1, pageSize));

        }
        public IActionResult Add()
        {
            AddOwnerViewModel addOwnerViewModel = new AddOwnerViewModel();
            return View(addOwnerViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddOwnerViewModel addOwnerViewModel)
        {

            if (ModelState.IsValid)
            {
                Owner newOwner = new Owner
                   
                {
                    Name = addOwnerViewModel.Name
                };
                context.Owners.Add(newOwner);
                context.SaveChanges();
                return Redirect("/Owner");
            }
            return View(addOwnerViewModel);
        }
        public async Task<IActionResult> ViewOwner(int id, int? page)
        {
            //TODO: #1 implement a paginatedList for ViewOwner Action
            List<OwnerLoad> items = context
                .OwnerLoads
                .Include(item => item.Load)
                .Where(cm => cm.OwnerID == id)
                .ToList();
            Owner owner = context.Owners.Single(m => m.ID == id);
         
            ViewOwnerViewModel viewModel = new ViewOwnerViewModel
            {
                Owner = owner,
                Items = items

            };
            int pageSize = 3;
            return View( (viewModel));
        }
     

        public IActionResult OwnerItems(int id)
        {
           
            List<OwnerLoad> items = context.
                OwnerLoads.
                Include(item => item.Load).
                Where(ol => ol.LoadID == id).
                ToList();
            Owner owner = context.Owners.Single(c => c.ID == id);
            OwnerItemViewModel ownerItem = new OwnerItemViewModel
            {
                Owner = owner,
                Items = items
            };

            return View(ownerItem);
        }

        public IActionResult AddItem(int id)
        {
           Owner owner = context.Owners.Single(o => o.ID == id);
            List<Load> loads = context.Loads.ToList();
            

            return View(new AddOwnerItemViewModel(owner, loads));

        }
        [HttpPost]
        public IActionResult AddItem(AddOwnerItemViewModel addOwnerItemViewModel)
        {
            if (ModelState.IsValid)
            {
                
                var loadID = addOwnerItemViewModel.LoadID;
                var ownerID = addOwnerItemViewModel.OwnerID;
                IList<OwnerLoad> existingItems = context.OwnerLoads
                    .Where(ol => ol.LoadID == loadID)
                    .Where(ol => ol.OwnerID == ownerID).ToList();
                if (existingItems.Count == 0)
                {
                    
                    OwnerLoad ownerItem = new OwnerLoad
                    {
                        Load = context.Loads.Single(o => o.ID == loadID),
                        Owner = context.Owners.Single(ol => ol.ID == ownerID)
                    };
                    context.OwnerLoads.Add(ownerItem);
                    context.SaveChanges();
                }
                return Redirect(string.Format("/Owner/ViewOwner/{0}", addOwnerItemViewModel.OwnerID));
            }
            return View(addOwnerItemViewModel);
        }

        public async Task<IActionResult> Expense(int? page)
        {
            var owners = from o in context.Owners
                         select o;
            int pageSize = 3;
            return View(await PaginatedList<Owner>.CreateAsync(owners.AsNoTracking(), page ?? 1, pageSize));

        }

        public async Task<IActionResult> ViewOwnerExpense(int id, int? page)
        {
            //TODO: #2 implement a paginatedList for ViewOwnerExenpense Action
            List<OwnerExpense> expenseItems = context.
               OwnerExpenses.
               Include(item => item.Expense).
               Where(ol => ol.OwnerID == id).
               ToList();
            Owner owner = context.Owners.Single(c => c.ID == id);
            ViewOwnerExpenseViewModel ownerExpenseItem = new ViewOwnerExpenseViewModel
            {
                Owner = owner,
                ExpenseItems = expenseItems
            };

            
            int pageSize = 3;
            return View(ownerExpenseItem);
        }

        
        
        public IActionResult OwnerExpenseItems(int id)
        {
           
            List<OwnerExpense> expenseItems = context.
                OwnerExpenses.
                Include(item => item.Expense).
                Where(ol => ol.ExpenseID == id).
                ToList();
            Owner owner = context.Owners.Single(c => c.ID == id);
            OwnerExpenseItemViewModel ownerExpenseItem = new OwnerExpenseItemViewModel
            {
                Owner = owner,
                ExpenseItems = expenseItems
            };

            return View(ownerExpenseItem);
        }


    
        
        
        public IActionResult AddExpenseItem(int id)
        {
            Owner owner = context.Owners.Single(o => o.ID == id);
            List<Expense> expenses = context.Expenses.ToList();
          

            return View(new AddOwnerExpenseItemViewModel(owner, expenses));

        }

   
        [HttpPost]
        public IActionResult AddExpenseItem(AddOwnerExpenseItemViewModel addOwnerExpenseItemViewModel)
        {
            //TODO: Display Category Name along item rather than the just the ID

            if (ModelState.IsValid)
            {
                
                var expenseID = addOwnerExpenseItemViewModel.ExpenseID;
                var ownerID = addOwnerExpenseItemViewModel.OwnerID;
                IList<OwnerExpense> existingItems = context.OwnerExpenses
                    .Where(ol => ol.ExpenseID == expenseID)
                    .Where(ol => ol.OwnerID == ownerID).ToList();
                if (existingItems.Count == 0)
                {

                    OwnerExpense ownerExpenseItem = new OwnerExpense
                    {
                        Expense = context.Expenses.Single(o => o.ID == expenseID),
                        Owner = context.Owners.Single(ol => ol.ID == ownerID)
                    };
                    context.OwnerExpenses.Add(ownerExpenseItem);
                    context.SaveChanges();
                }

                return Redirect(string.Format("/Owner/ViewOwnerExpense/{0}", addOwnerExpenseItemViewModel.OwnerID));
            }
            return View(addOwnerExpenseItemViewModel);
        }


        public IActionResult Remove(int ID)
        {
            var o = context.Owners.Single(e => e.ID == ID);
            if (o != null)
                context.Owners.Remove(o);

            context.SaveChanges();

            return Redirect("/Owner");


        }
       
        public async Task<IActionResult> Edit(int id)
        {
            var owner = context.Owners.SingleOrDefault((l) => l.ID == id);
            if (owner == null)
            {
                return NotFound();
            }
           
            return View(new AddOwnerViewModel());
        }


        [HttpPost]
        public async Task<IActionResult> Edit(AddOwnerViewModel addOwnerViewModel)
        {
            var owner = context.Owners.SingleOrDefault((l) => l.ID == addOwnerViewModel.ID);
            if (owner == null)
            {
                return NotFound();
            }
            

            var viewModel = new AddOwnerViewModel(owner);

            

            return View(viewModel);
        }
    }
}

SaafiSystems/Views/Owner/Add.cshtml
@model SaafiSystems.ViewModels.AddOwnerViewModel

<div class="page-header" style="background:white">
    <h1 style=" font-size: 21px;color: #0b131d; font-weight: 400;font-size: 21px;margin-top: 20px;margin-bottom: 10px;font-family: inherit;font-weight: 400;line-height: 1.1;color: inherit;margin: .67em 0; font-size: 2em; box-sizing: border-box;display: block;font-size: 2em; font-weight: bold;">
        Add Owner Operator
        <a asp-controller="Owner" asp-action="Add" class="hidden-xs btn btn-primary pull-right">+ Add Owner-Operator</a> <a asp-controller="Owner" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ Add Owner-Operator</a>
        <a asp-controller="Load" asp-action="Add" class="hidden-xs btn btn-success pull-right">+ New Payroll Entry</a> <a asp-controller="Load" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ New Load Entry</a>
    </h1>
</div>
<form asp-controller="Owner" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <input type="submit" class="hidden-xs btn btn-success" value=" + Submit New Owner" />


</form>

SaafiSystems/Views/Owner/AddExpenseItem.cshtml
@model SaafiSystems.ViewModels.AddOwnerExpenseItemViewModel

<div class="page-header" style="background:white">
    <h1 style=" font-size: 21px;color: #0b131d; font-weight: 400;font-size: 21px;margin-top: 20px;margin-bottom: 10px;font-family: inherit;font-weight: 400;line-height: 1.1;color: inherit;margin: .67em 0; font-size: 2em; box-sizing: border-box;display: block;font-size: 2em; font-weight: bold;">
        Add Expense Entry
        <a asp-controller="ExpenseCategory" asp-action="Add" class="hidden-xs btn btn-primary pull-right">+ Add Category</a> <a asp-controller="ExpenseEntry" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ Add Category</a>
        <a asp-controller="Expense" asp-action="Add" class="hidden-xs btn btn-success pull-right">+ New Expense Entry</a> <a asp-controller="Expense" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ New Expense Entry</a>

    </h1>
</div>

@*<form asp-controller="Owner" asp-action="AddExpenseItem" method="post">
    <table class="table table-striped " style="width: 100%; max-width: 100%; margin-bottom: 20px; background-color: transparent; border-spacing: 0; border-collapse: collapse; box-sizing: border-box; display: table;border-collapse: separate; border-spacing: 2px; border-color: grey; font-size: 14px; line-height: 1.42857143;">


        <tbody style="display: table-row-group;vertical-align: middle;border-color: inherit;">

            <tr style="display: table-row; vertical-align: inherit; border-color: inherit;">

                <td style="padding: 8px;line-height: 1.42857143;vertical-align: top; border-top: 1px solid #ddd;">
                    <div class="form-group">
                        <label asp-for="ExpenseID">
                            <select class="form-control" asp-for="ExpenseID" asp-items="@Model.Expenses"></select>
                            <span asp-validation-for="ExpenseID"></span>
                        </label>

                    </div>
                    <input type="hidden" name="OwnerID" value="@Model.Owner.ID" />
                    <input type="submit" class="hidden-xs btn btn-success" value=" + Submit Entry" />
                </td>

            </tr>

        </tbody>

    </table>

</form>*@



<form asp-controller="Owner" asp-action="AddExpenseItem" method="post">
    <table class="table table-striped ">
        <tr>
            <th>Date</th>
            <th>Reference</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Amount</th>
            <th>Cartegory</th>
            <th></th>
            <th>Assign to Owner</th>

        </tr>

        @foreach (var expense in Model.Expenses)
        {

            <tr>
                <td> @expense.Date </td>
                <td> @expense.Reference </td>
                <td> @expense.Description </td>
                <td> @expense.Owner </td>
                <td> @expense.Amount </td>
                <td> @expense.ExpenseCategory </td>




                <td></td>
                <td>


                    <input type="checkbox" name="ExpenseID" id="@expense.ID" value="@expense.ID">
                    <input type="hidden" name="OwnerID" value="@Model.Owner.ID" />



                    <input type="submit" class="hidden-xs btn btn-info btn-xs pull-right" value=" + Assign Item" />

                </td>

            </tr>

        }

    </table>

</form>






@*@model SaafiSystems.ViewModels.AddOwnerItemViewModel

    @{
        ViewBag.Titel = "Add Item to Owner" + @Model.Owner.Name;
    }
    <form asp-controller="Owner" asp-action="AddItem" method="post">
        <div class="form-group">
            <label asp-for="LoadID">
                <select asp-for="LoadID" asp-items="@Model.Loads"></select>
                <span asp-validation-for="LoadID"></span>
            </label>

        </div>
        <input type="hidden" name="OwnerID" value="@Model.Owner.ID" />
        <input type="submit" value="Add Item" />
    </form>*@

SaafiSystems/Views/Owner/OwnerExpenseItems.cshtml
@model SaafiSystems.ViewModels.OwnerExpenseItemViewModel


<div class="page-header" style="background:white">
    <h1 style=" font-size: 21px;color: #0b131d; font-weight: 400;font-size: 21px;margin-top: 20px;margin-bottom: 10px;font-family: inherit;font-weight: 400;line-height: 1.1;color: inherit;margin: .67em 0; font-size: 2em; box-sizing: border-box;display: block;font-size: 2em; font-weight: bold;">
     @{ ViewBag.Title = Model.Owner.Name;}
        <a asp-controller="Owner" asp-action="AddExpenseItem" asp-route-id="@Model.Owner.ID" class="hidden-xs btn btn-primary pull-right">+ Add New Item</a> <a asp-controller="Owner" asp-action="AddExpenseItem" class="visible-xs-block mobile-add btn-block btn btn-success">+ Add New Item</a>
        <a asp-controller="Owner" asp-action="Add" class="hidden-xs btn btn-success pull-right">+ New Owner</a> <a asp-controller="Owner" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ New Owner</a>
    </h1>
</div>

@if (Model.ExpenseItems.Count == 0)
{
    ViewBag.Title = Model.Owner.Name;
    <p>No load entries yet!</p>
}
<form asp-controller="Expense" asp-action="Remove" method="post">
    <table class="table table-striped ">

        <tr>
            <th>Date</th>
            <th>Reference</th>

            <th>Description</th>
            <th>Owner</th>
            <th>Category</th>
            <th>Amount</th>
            <th class="pull-right">Action</th>
            <th></th>
        </tr>

        @foreach (var item in Model.ExpenseItems)
        {
            <tr>
                <td>@item.Expense.Date</td>
                <td>@item.Expense.Reference</td>

                <td>@item.Expense.Description</td>
                <td>@item.Expense.Owner</td>
                <td>@item.Expense.ExpenseCategory</td>
                <td>@item.Expense.Amount</td>

                <td>
                    <a href="/expense/edit/@item.Expense.ID" class="btn btn-info btn-xs">Edit</a>
                    @*@*<input type="checkbox" name="expenseIds" id="@expense.ID" value="@expense.ID" class="btn btn-danger btn-sm" />*@
                    @*<input type="submit" value="Delete" class="btn btn-info btn-sm" />*@
                </td>
                <td>
                    <a href="/expense/remove/@item.Expense.ID" class="btn btn-danger btn-xs">Delete</a>
                    @*<input type="submit" value="Edit" class="btn btn-info btn-sm" />*@
                </td>
            </tr>
        }
    </table>

    

</form>\

<a asp-controller="Expense" asp-action="Add" class="btn btn-success btn-sm">Add Expense Item</a>
<a asp-controller="Owner" class="pull-right"> <span class="btn btn-info btn-sm">Owner Operators</span> </a>
@*@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled btn">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled btn">
    Next
</a>
</br>*@

SaafiSystems/Views/Owner/ViewOwnerExpense.cshtml
@model SaafiSystems.ViewModels.ViewOwnerExpenseViewModel

@{
    ViewBag.Title = Model.Owner.Name;
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


<h1>@ViewBag.Title</h1>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="page-header" style="background:white">
    <h1 style=" font-size: 21px;color: #0b131d; font-weight: 400;font-size: 21px;margin-top: 20px;margin-bottom: 10px;font-family: inherit;font-weight: 400;line-height: 1.1;color: inherit;margin: .67em 0; font-size: 2em; box-sizing: border-box;display: block;font-size: 2em; font-weight: bold;">
        Expense Entries
        <form asp-controller="Reports" asp-action="Index" class="navbar-form navbar-left" role="search" method="get">
            <div class="form-group">
                <p>
                    <input type="text" name="searchString" class="form-control" placeholder="Search your trips, loads and more" value="@ViewData["CurrentFilter"]" />
                    <input type="submit" value="Search" class="btn btn-group-xs " />
                </p>
            </div>

        </form>
        <a asp-controller="ExpenseCategory" asp-action="Add" class="hidden-xs btn btn-primary pull-right">+ Add Category</a> <a asp-controller="LoadCategory" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ Add Load Category</a>
        <a asp-controller="Expense" asp-action="Add" class="hidden-xs btn btn-success pull-right">+ New Expense Item</a> <a asp-controller="Load" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ New Trip</a>
    </h1>
</div>

@if (Model.ExpenseItems.Count == 0)
{
    <p>No Owner Loads Yet!</p>
}


<table class="table table-striped">

    <tr>
        <th>Date</th>
        <th>Reference</th>
        <th>Description</th>
        <th>Owner</th>
        <th>Amount</th>
        <th>Category</th>
        <th></th>
        <th class="pull-right">Action</th>
        <th></th>

    </tr>

    @foreach (var item in Model.ExpenseItems)

    {
        <tr>
            <td>@item.Expense.Date</td>
            <td>@item.Expense.Reference</td>

            <td>@item.Expense.Description</td>
            <td>@item.Expense.Owner</td>
            <td>@item.Expense.Amount</td>
            <td>
                <a asp-controller="Load"
                   asp-action="Edit"
                   asp-route-id="@item.Expense.ID">@item.Expense.ExpenseCategoryID</a>
            </td>
       
            <td>

                <a href="/load/edit/@item.Expense.ID" class="btn btn-info btn-xs">Edit</a>
                @*@*<input type="checkbox" name="expenseIds" id="@expense.ID" value="@expense.ID" class="btn btn-danger btn-sm" />*@
                @*<input type="submit" value="Delete" class="btn btn-info btn-sm" />*@
            </td>
            <td>
                <a href="/load/remove/@item.Expense.ID" class="btn btn-danger btn-xs">Delete</a>
                @*<input type="submit" value="Edit" class="btn btn-info btn-sm" />*@
            </td>
            <td></td>
        </tr>
    }
</table>
<a asp-controller="Owner" asp-action="AddExpenseItem" asp-route-id="@Model.Owner.ID" class="btn btn-success btn-xs">+ Assign Expense Item</a>

<a asp-controller="Load" asp-action="Add" class="btn btn-info btn-xs pull-right">+ Add Trip</a>
<br />
<br />


@*{
    //TODO: #1 implement a paginatedList for ViewOwner Action

    }*@

@*@{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled btn">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled btn">
        Next
    </a>
    </br>*@