SaafiSystems/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SaafiSystems.Models
{
    public class Expense
    {
  
        public int ID {get; set;}

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? Date { get; set; }
    
        public string Reference { get; set; }
        public string Owner { get; set; }
        public string Description { get; set; }
        public int Amount { get; set; }

        [Required(ErrorMessage =("Select a Catgory or Add a new one!"))]
        
        public int ExpenseCategoryID { get; set; }
        public ExpenseCategory ExpenseCategory { get; set; }

        public List<OwnerExpense> OwnerExpenses { get; set; }
    }
}

SaafiSystems/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using SaafiSystems.Models;
using System.Collections.Generic;
using SaafiSystems.ViewModels;
using SaafiSystems.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace SaafiSystems.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly SaafiDbContext context;

        public ExpenseController(SaafiDbContext dbContext)
        {
            this.context = dbContext;
        }

        // GET: /<controller>/
        public async Task< IActionResult> Index(int? page)
        {
            //.Include(c => c.Owner).ToList();
            var expenses = from e in context.Expenses.Include(c => c.ExpenseCategory)
                          select e;
            int pageSize = 3;
            return View(await PaginatedList<Expense>.CreateAsync(expenses.AsNoTracking(), page ?? 1, pageSize));
           
        }

        public IActionResult Add()
        {
            IList<ExpenseCategory> expenseCategories = context.ExpenseCategories.ToList();
            AddExpenseViewModel addExpenseViewModel =
                new AddExpenseViewModel(context.ExpenseCategories.ToList(), null);
            return View(addExpenseViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddExpenseViewModel addExpenseViewModel)
        {
            if (ModelState.IsValid)
            {
                ExpenseCategory newCategory =
                    context.ExpenseCategories.Single(c => c.ID == addExpenseViewModel.ExpenseCategoryID);
                // Add the new cheese to my existing cheeses
                Expense newExpense = new Expense
                {

                    Date = addExpenseViewModel.Date,
                    Reference = addExpenseViewModel.Reference,
                    Owner = addExpenseViewModel.Owner,
                  
                    Description = addExpenseViewModel.Description,
                    Amount = addExpenseViewModel.Amount,
                    ExpenseCategory = newCategory
                  
                    
                };

                context.Expenses.Add(newExpense);
                context.SaveChanges();

                return Redirect("/Expense");
            }

            return View(addExpenseViewModel);
        }

        public IActionResult Remove(int ID)
        {
            var exp = context.Expenses.Single(e => e.ID == ID);
            if (exp != null)
                context.Expenses.Remove(exp);

            context.SaveChanges();

            return Redirect("/Expense");

       
        }

        [HttpPost]
        public IActionResult Remove(int[] expenseIds)
        {
            foreach (int expenseId in expenseIds)
            {
                Revenue theRevenue = context.Revenues.Single(c => c.ID == expenseId);
                context.Revenues.Remove(theRevenue);
            }

            context.SaveChanges();

            return Redirect("/Expense");
        }
        [HttpPost]
        public IActionResult Category(int id)
        {
            if (id == 0)
            {
                Redirect("/Category");
            }

            ExpenseCategory theCategory = context.ExpenseCategories
                .Include(cat => cat.Expenses)
                .Single(cat => cat.ID == id);

            /* 
             * IList<Cheese> theCheese = Context.Cheeses
             * .Include(c => c.Category)
             * .Single(c => c.CategoryID ==id)
             .ToList();*/

            ViewBag.Title = "Expenses in Category" + theCategory.Name;
            return View("Index", theCategory.Expenses);
        }
      
        public ViewResult Search(string searchString)
        {
           //IList<Expense> expenses = context.Expenses.Include(c => c.ExpenseCategory).Include(c => c.Owner).ToList();
            var expenses = from c in context.Expenses.Include(c => c.ExpenseCategory).Include(c => c.Owner).ToList()
            select c;

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                expenses = context.Expenses.Where(c =>
               c.Reference.Contains(searchString)
                ||

               c.Date.ToString().Contains(searchString) ||

               c.Description.Contains(searchString) ||

               c.Owner.Contains(searchString));

          
            }
            
            return View(expenses);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var expense = context.Expenses.SingleOrDefault((l) => l.ID == id);
            if (expense == null)
            {
                return NotFound();
            }
            List<ExpenseCategory> newExpenseCategory =
                    new List<ExpenseCategory>() { context.ExpenseCategories.Single(c => c.ID == expense.ExpenseCategoryID) };
            return View(new AddExpenseViewModel(newExpenseCategory, expense));
        }


        [HttpPost]
        public async Task<IActionResult> Edit(AddExpenseViewModel addExpenseViewModel)
        {
            var expense = context.Expenses.SingleOrDefault((l) => l.ID == addExpenseViewModel.ID);
            if (expense == null)
            {
                return NotFound();
            }
            var newExpenseCategories = context.ExpenseCategories;

            var viewModel = new AddExpenseViewModel(newExpenseCategories, expense);

            var existingExpenseCategory = context.ExpenseCategories.SingleOrDefault(c => c.ID == expense.ExpenseCategoryID);

            if (existingExpenseCategory != null)
            {
                viewModel.ExpenseCategory = existingExpenseCategory;
                viewModel.ExpenseCategoryID = existingExpenseCategory.ID;
            }

            return View(viewModel);
        }
    }
}

SaafiSystems/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using SaafiSystems.Models;
using System.Data;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SaafiSystems.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList;
using PagedList.Core;
using SaafiSystems.Models.MonthlyRevenueViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SaafiSystems.Controllers
{
    public class ReportsController : Controller
    {
        private readonly SaafiDbContext context;
        public ReportsController(SaafiDbContext dbcontext)
        {
            context = dbcontext;
        }

        // GET: Reports
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";



            ViewData["OwnerSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Owner_desc" : "";
            ViewData["categorytortParm"] = String.IsNullOrEmpty(sortOrder) ? "category_desc" : "";

            ViewData["CurrentFilter"] = searchString;





            ViewBag.CurrentFilter = searchString;

            var loads = from l in context.Loads
                        select l;


            if (searchString != null)
            {

                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                loads = loads.Where(l => l.Date.ToString().Contains(searchString) || l.Reference.Contains(searchString) || l.Owner.ToUpper().Contains(searchString.ToUpper()) || l.Description.ToUpper().Contains(searchString.ToUpper()) || l.LoadCategory.ToString().Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Owner_desc":
                    loads = loads.OrderByDescending(l => l.Owner);
                    break;
                case "Date":
                    loads = loads.OrderBy(l => l.Date);
                    break;
                case "date_desc":
                    loads = loads.OrderByDescending(l => l.Date);
                    break;
                default:
                    loads = loads.OrderBy(l => l.LoadCategory);
                    break;
            }

            int pageSize = 3;
            return View(await PaginatedList<Load>.CreateAsync(loads.AsNoTracking(), page ?? 1, pageSize));
        }

        public IActionResult Search(string searchTerm)
        {
            var loads = context.Loads.Where(c => c.Description.Contains(searchTerm)).ToList();
            return View(loads);

        }

        public async Task<ActionResult> MonthlyRevenue()
        {
            IQueryable<MonthlyRevenue> data =
                from load in context.Loads
                group load by load.Date into monthlyRevenueGroup
                select new MonthlyRevenue()
                {
                    Date = monthlyRevenueGroup.Key,
                    RevenueTotal = monthlyRevenueGroup.Count()
                };
            return View(await data.AsNoTracking().ToListAsync());
        }



    }
}








//public ActionResult DailySales()
//{

//    var list = context.Loads.Where(x => DbFunctions.DiffDays(x.Date, DateTime.Now) == 0).ToList();
//    return View(list);
//}



//public ActionResult DailySalesFor(DateTime getDate)
//{
//    var list = db.Sales.Where(x => DbFunctions.DiffDays(x.Date, getDate) == 0).ToList();
//    return PartialView("_DailySalesPartialView", list);
//}

////    //Staffs
////    public ActionResult EmployeesReports()
//    {
//        return null;
//    }
//    /*
//        //Monthly Sales
//        public ActionResult MonthlySalesByDate()
//        {

//            int year = 2014;
//            int month = 12;
//            var query = db.Sales.Where(x => x.Date.Year == year && x.Date.Month == month).GroupBy(x => x.Date).Select(g => new DayTotalVM
//            {
//                Day = g.Key.Day,
//                Total = g.Sum(x => x.GrandTotal)
//            });
//            int daysInMonth = DateTime.DaysInMonth(year, month);
//            List<DayTotalVM> days = new List<DayTotalVM>();
//            for (int i = 1; i < daysInMonth + 1; i++ )
//            {
//                DayTotalVM item = new DayTotalVM() { Day = i};
//                DayTotalVM ex = query.Where(x => x.Day == i).FirstOrDefault();
//                if(ex != null)
//                {
//                    item.Total = ex.Total;
//                }
//                days.Add(item);
//            }
//            SalesVM model = new SalesVM() 
//            { 
//                Date = new DateTime(year, month,1),
//                Days = days
//            };
//            return View(model);
//        }
//*/

//    /// <summary>
//    /// Display monthly Sales for each day in a month
//    /// </summary>
//    /// <returns></returns>
//    public ActionResult MonthlySalesByDate()
//    {
//        int year = 2014;
//        int month = 12;
//        int daysInMonth = DateTime.DaysInMonth(year, month);
//        var days = Enumerable.Range(1, daysInMonth);
//        var query = db.Sales.Where(x => x.Date.Year == year && x.Date.Month == month).OrderBy(x => x.Date).Select(g => new
//        {
//            Day = g.Date.Day,
//            Total = g.GrandTotal
//        });
//        var model = new SalesVM
//        {
//            Date = new DateTime(year, month, 1),
//            Days = days.GroupJoin(query, d => d, q => q.Day, (d, q) => new DayTotalVM
//            {
//                Day = d,
//                Total = q.Sum(x => x.Total)
//            }).ToList()
//        };
//        return View(model);
//    }



//    //Returns Monthly sales based on a parameter
//    [HttpPost]
//    public ActionResult MonthlySalesByDate(string _year, string _month)
//    {
//        //assign incoming values to the variables
//        int year = 0, month = 0;
//        //check if year is null
//        if (string.IsNullOrWhiteSpace(_year) && _month != null)
//        {
//            year = DateTime.Now.Date.Year;
//            month = Convert.ToInt32(_month.Trim());
//        }
//        else
//        {
//            year = Convert.ToInt32(_year.Trim());
//            month = Convert.ToInt32(_month.Trim());
//        }
//        //calculate ttal number of days in a particular month for a that year 
//        int daysInMonth = DateTime.DaysInMonth(year, month);
//        var days = Enumerable.Range(1, daysInMonth);
//        var query = db.Sales.Where(x => x.Date.Year == year && x.Date.Month == month).OrderBy(x => x.Date.Day).Select(g => new
//        {
//            Day = g.Date.Day,
//            Total = g.GrandTotal
//        });
//        var model = new SalesVM
//        {
//            Date = new DateTime(year, month, 1),
//            Days = days.GroupJoin(query, d => d, q => q.Day, (d, q) => new DayTotalVM
//            {
//                Day = d,
//                Total = q.Sum(x => x.Total)
//            }).ToList()
//        };
//        return View(model);
//    }




//    public List<DayTotalVM> MonthlySalesByDate_forCharts(int yr, int mnt)
//    {
//        int year = yr;
//        int month = mnt;
//        int daysInMonth = DateTime.DaysInMonth(year, month);
//        var days = Enumerable.Range(1, daysInMonth);
//        var query = db.Sales.Where(x => x.Date.Year == year && x.Date.Month == month).Select(g => new
//        {
//            Day = g.Date.Day,
//            Total = g.GrandTotal
//        });
//        SalesVM model = new SalesVM
//        {
//            Date = new DateTime(year, month, 1),
//            Days = days.GroupJoin(query, d => d, q => q.Day, (d, q) => new DayTotalVM
//            {
//                Day = d,
//                Total = q.Sum(x => x.Total)
//            }).ToList()
//        };
//        return model.Days.ToList();
//    }
//    //********************************************************************
//    /// <summary>
//    /// Yearly Sales
//    /// </summary>
//    /// <param name="year"></param>
//    /// <returns></returns>
//    public ActionResult YearlySalesByMonth(string year)
//    {
//        int _year = 0;
//        int _toYear = 0;
//        if (string.IsNullOrWhiteSpace(year))
//        {
//            _year = DateTime.Now.Year;
//            _toYear = _year + 1;
//        }
//        else
//        {
//            _year = Convert.ToInt32(year);
//            _toYear = _year + 1;
//        }

//        //    int _year = DateTime.Now.Year;
//        //    int _toYear = _year + 1;
//        var query = db.Sales.Where(s => (s.Date.Year >= _year && s.Date.Year < _toYear));
//        // YearlyReportVM _Model = new YearlyReportVM();
//        List<MonthTotalVM> _Model = new List<MonthTotalVM>();

//        for (int i = 1; i < 13; i++)
//        {
//            decimal _grandTotal = 0;
//            decimal temp = 0;
//            temp = query.Where(x => x.Date.Month == i).Sum(x => (decimal?)(x.GrandTotal)) ?? 0;

//            _grandTotal = temp;

//            MonthTotalVM model = new MonthTotalVM()
//            {
//                Year = _year,
//                Month = i,
//                GrandTotal = _grandTotal
//            };
//            _Model.Add(model);
//        }

//        return View(_Model.ToList());
//    }



//    public List<MonthTotalVM> YearlySalesByMonth_forCharts(string year)
//    {
//        int _year = 0;

SaafiSystems/Views/Reports/Expense.cshtml
@model SaafiSystems.ViewModels.ViewOwnerViewModel
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="page-header" style="background:white">
    <h1 style=" font-size: 21px;color: #0b131d; font-weight: 400;font-size: 21px;margin-top: 20px;margin-bottom: 10px;font-family: inherit;font-weight: 400;line-height: 1.1;color: inherit;margin: .67em 0; font-size: 2em; box-sizing: border-box;display: block;font-size: 2em; font-weight: bold;">

        <a asp-controller="LoadCategory" asp-action="Add" class="hidden-xs btn btn-primary pull-right">+ Add Category</a> <a asp-controller="LoadCategory" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ Add Category</a>
        <a asp-controller="Load" asp-action="Add" class="hidden-xs btn btn-success pull-right">+ New Load Entry</a> <a asp-controller="Load" asp-action="Add" class="visible-xs-block mobile-add btn-block btn btn-success">+ New Load Entry</a>

    </h1>
</div>
<a asp-controller="Expense">ALl Expenses</a>
<form asp-controller="Owner" asp-action="ViewOwner" method="post">
    <table class="table table-striped " style="width: 100%; max-width: 100%; margin-bottom: 20px; background-color: transparent; border-spacing: 0; border-collapse: collapse; box-sizing: border-box; display: table;border-collapse: separate; border-spacing: 2px; border-color: grey; font-size: 14px; line-height: 1.42857143;">


        <tbody style="display: table-row-group;vertical-align: middle;border-color: inherit;">

            <tr style="display: table-row; vertical-align: inherit; border-color: inherit;">

                <td style="padding: 8px;line-height: 1.42857143;vertical-align: top; border-top: 1px solid #ddd;">
                    <div class="form-group">
                        <label asp-for="OwnerID">
                            <select asp-for="OwnerID" asp-items="Model.Owners"></select>
                            <span asp-validation-for="OwnerID"></span>
                        </label>

                    </div>

                    <input type="submit" class="hidden-xs btn btn-success" value=" +   Select Owner Operator" />
                </td>

            </tr>

        </tbody>

    </table>

</form>

SaafiSystems/Views/Reports/Index.cshtml
@model PaginatedList<SaafiSystems.Models.Load>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@using PagedList.Core;

@{
    ViewBag.Title = "Loads";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<form asp-controller="Reports" asp-action="Index" class="navbar-form navbar-left" role="search" method="get">
    <div class="form-group">
        <p>
            <input type="text" name="searchString" class="form-control" placeholder="Search your trips, loads and more" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-group-xs " />
        </p>
    </div>
</form>

  


<div style="border-bottom: 3px solid #e8e8e8; padding-bottom: 9px;
    margin: 40px 0 20px; display: block; color: #595952; font-size: 34px;
    line-height: 1.42857143; box-sizing: border-box;">
    All Reports
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th>Reference</th>

            <th>Description</th>
          
            <th> <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Owner</a> @Html.ActionLink("Owner", "Index", new { sortOrder = ViewBag.OwnerSortParm })</th>

            <th>Amount</th>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Category</a>  @Html.ActionLink("Category", "Index", new { sortOrder = ViewBag.CategorySortParm })</th>
            <th class="pull-right">Action</th>
            <th></th>

        </tr>
    </thead>
    <tbody>
        @foreach (var load in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => load.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => load.Reference)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => load.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => load.Owner)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => load.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => load.LoadCategory)
                </td>
                <td> </td>
                <td></td>

                <td>
                    <input type="checkbox" name="loadIds" id="@load.ID" value="@load.ID" class="btn btn-danger btn-sm" />
                    <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
                </td>
                <td>
                    <input type="checkbox" name="loadIds" id="@load.ID" value="@load.ID" class="btn btn-danger btn-sm" />
                    <input type="submit" value="Edit" class="btn btn-info btn-sm" />
                </td>
</tr>
        }

</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled btn">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled btn">
    Next
</a>
</br>

<strong style=" color: #0090df;color: #337ab7; text-decoration: none;background-color: transparent; box-sizing: border-box; color: -webkit-link;  cursor: auto; font-weight: bold;    font-weight: bold; font-size: 18px; line-height: 2;     box-sizing: border-box;">


    <a>
        Profit and Loss
    </a><br />
    <a asp-controller="Reports" asp-action="expense">
        Expense Report
    </a><br />
    <a>
        Fuel Mileage
    </a><br />
    <a>
        IFTA Report
    </a><br />
</strong>

SaafiSystems/Views/Reports/MonthlyRevenue.cshtml
@model IEnumerable<SaafiSystems.Models.MonthlyRevenueViewModel.MonthlyRevenue>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewData["Title"] = "Total Trips By Month";
}

<h2>Total Trips By Month"</h2>

<table>
    <tr>
        <th>
            Trip Date
        </th>
        <th>
            Trips
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @item.RevenueTotal
            </td>
        </tr>
    }
</table>

SaafiSystems/Views/Reports/Search.cshtml
@model IEnumerable<SaafiSystems.Models.Load>



            Search Loads:
            <form asp-action="Index" method="get">
                <div class="form-actions no-color">
        <p>
            <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>
<a asp-action="Index">Back to Full List</a>
       





<div style="border-bottom: 3px solid #e8e8e8; padding-bottom: 9px;
    margin: 40px 0 20px; display: block; color: #595952; font-size: 34px;
    line-height: 1.42857143; box-sizing: border-box;">
    All Reports
</div>
<table class="table table-striped">

    <tr>
        <th>Date</th>
        <th>Reference</th>

        <th>Description</th>
        <th>Owner</th>
        <th>Amount</th>

        <th class="pull-right">Action</th>
        <th></th>

    </tr>

    @foreach (var load in Model)
    {
        <tr>
            <td>@load.Date</td>
            <td>@load.Reference</td>

            <td>@load.Description</td>
            <td>@load.Owner</td>
            <td>@load.Amount</td>

            <td> </td>
            <td></td>

            <td>
                <input type="checkbox" name="loadIds" id="@load.ID" value="@load.ID" class="btn btn-danger btn-sm" />
                <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
            </td>
            <td>
                <input type="checkbox" name="loadIds" id="@load.ID" value="@load.ID" class="btn btn-danger btn-sm" />
                <input type="submit" value="Edit" class="btn btn-info btn-sm" />
            </td>
        </tr>
    }
</table>

<strong style=" color: #0090df;color: #337ab7; text-decoration: none;background-color: transparent; box-sizing: border-box; color: -webkit-link;  cursor: auto; font-weight: bold;    font-weight: bold; font-size: 18px; line-height: 2;     box-sizing: border-box;">


    <a>
        Profit and Loss
    </a><br />
    <a asp-controller="Reports" asp-action="expense">
        Expense Report
    </a><br />
    <a>
        Fuel Mileage
    </a><br />
    <a>
        IFTA Report
    </a><br />
</strong>